os: osx
language: swift
osx_image: xcode10.1
script: xcodebuild clean test -workspace TestTravisCI.xcworkspace -scheme "TestTravisCI" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone X" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO